name: validate mls.json
on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
             pip install jsonschema
             python -mjson.tool mls.json > /dev/null
             jsonschema -i mls.json config.schema
  
